from enum import Enum, auto

class Operand(Enum):
    NOP = auto()
    HALT = auto()
    LD = auto()
    ST = auto()
    MOV = auto()
    LI = auto()
    VID = auto()
    ADD = auto()
    ADDI = auto()
    SUB = auto()
    SUBI = auto()
    MULT = auto()
    MULTI = auto()
    DIV = auto()
    DIVI = auto()
    QUOT = auto()
    QUOTI = auto()
    AND = auto()
    ANDI = auto()
    OR = auto()
    ORI = auto()
    XOR = auto()
    XORI = auto()
    NOT = auto()
    SHL = auto()
    SHLI = auto()
    SHR = auto()
    SHRI = auto()
    RR = auto()
    RRI = auto()
    RL = auto()
    RLI = auto()
    AR = auto()
    ARI = auto()
    INC = auto()
    DEC = auto()
    JMP = auto()
    JEQ = auto()
    JNE = auto()
    JG = auto()
    JLE = auto()
    JL = auto()
    JGE = auto()
    JNZ = auto()
    JZ = auto()
    JNC = auto()
    JC = auto()
    CALL = auto()
    RTRN = auto()
    PUSH = auto()
    PUSHI = auto()
    POP = auto()
    CMP = auto()
    CMPI = auto()
    LABEL = auto()

    def negate(self):
        if Operand.JEQ.value > self.value < Operand.JC.value:
            raise ValueError(f"this is not a jump: {self}")
        if self.value & 1: # check if odd
            return Operand(self.value - 1)
        else:
            return Operand(self.value + 1)
